# This file is part of the django-environ.
#
# Copyright (C) 2021 Serghei Iakovlev <egrep@protonmail.ch>
# Copyright (C) 2013-2021 Daniele Faraglia
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+.x'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }} on ${{ matrix.os }}

    # The maximum number of minutes to let a workflow run
    # before GitHub automatically cancels it. Default: 360
    timeout-minutes: 30

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10.0-beta.1'
          - 'pypy-3.7'
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      - name: Success Reporting
        if: success()
        run: git log --format=fuller -5
